In [2]:

import numpy as np

In [ ]:
arr = np.random.randint(1,101,size=10)
print(arr)

[58 50 57 96 35 51 78 28 63 34]


In [12]:
# 1.a:
max_element = np.max(arr)
print("max element:",max_element)

max element: 96


In [8]:
# 1.b :
min_element = np.min(arr)
print("minimum element :",min_element)

minimum element : 28


In [10]:
#  1.c :
mean = np.mean(arr)
print("mean : " ,mean)

mean :  55.0


In [11]:
# 1.d :
s = np.sum(arr)
print("sum of the elemnents :", s)

sum of the elemnents : 550


In [17]:
# 1.e :
max_index = np.argmax(arr)
print("index of the max element : ",max_index)

index of the max element :  3


In [18]:
# 1.f :
min_index  = np.argmin(arr)
print("index of minimum element: ",min_index)

index of minimum element:  7


In [25]:
arr=np.sort(arr)
print(arr)

[28 34 35 50 51 57 58 63 78 96]


In [3]:
arr = np.random.randint(1,101,10)
print(arr)

[78 32 16 29 36 45 51 99  3 25]
