In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,21,size=(3,3))


In [7]:
# 2.a :
print("entire array : \n",arr)

entire array : 
 [[13 18 11]
 [19 12  4]
 [ 5  7  4]]


In [9]:
# 2.b:
print("first row :",arr[0])

first row : [13 18 11]


In [14]:
# 2.c :
print("second column : ", arr[:,1])

second column :  [18 12  7]


In [15]:
# 2.d : 
print("element at positiion (2,2)",print(arr[2,2]))

4
element at positiion (2,2) None


In [19]:
#  2.e:
print("subarray containing first two rows and columns : \n",arr[:2,:2])

subarray containing first two rows and columns : 
 [[13 18]
 [19 12]]


In [22]:
# 2.f :
arr[1,1] = 99 
print("modified array : \n",arr)

modified array : 
 [[13 18 11]
 [19 99  4]
 [ 5  7  4]]
